apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: evalhub
    app.kubernetes.io/name: trustyai-service-operator
  name: trustyai-service-operator-evalhub-resource-manager-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trustyai-service-operator-evalhub-resource-manager
subjects:
- kind: ServiceAccount
  name: trustyai-service-operator-controller-manager
  namespace: system
