# permissions for end users to view guardrailsorchestrators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: trustyai-service-operator
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: guardrailsorchestrator-viewer-role
rules:
- apiGroups:
  - trustyai.opendatahub.io
  resources:
  - guardrailsorchestrators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - trustyai.opendatahub.io
  resources:
  - guardrailsorchestrators/status
  verbs:
  - get
