# permissions for end users to edit guardrailsorchestrators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: trustyai-service-operator
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: guardrailsorchestrator-editor-role
rules:
- apiGroups:
  - trustyai.opendatahub.io
  resources:
  - guardrailsorchestrators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - trustyai.opendatahub.io
  resources:
  - guardrailsorchestrators/status
  verbs:
  - get
