resources:
  - service_account.yaml
  - role.yaml
  - role_binding.yaml
  - leader_election_role.yaml
  - leader_election_role_binding.yaml
  - auth_proxy_service.yaml
  - auth_proxy_role.yaml
  - auth_proxy_role_binding.yaml
  - auth_proxy_client_clusterrole.yaml
  - evalhub_proxy_role.yaml
  - evalhub_jobs_proxy_role.yaml
  - evalhub_resource_manager_role.yaml
  - evalhub_resource_manager_binding.yaml
  - nemoguardrail_editor_role.yaml
  - nemoguardrail_viewer_role.yaml
  - trustyaiservice_editor_role.yaml
  - trustyaiservice_viewer_role.yaml
  - non_admin_lmeval_role.yaml
  - default_lmeval_user_rolebinding.yaml
