resources:
  - service_account.yaml
  - role.yaml
  - role_binding.yaml
  - leader_election_role.yaml
  - leader_election_role_binding.yaml
  - auth_proxy_service.yaml
  - auth_proxy_role.yaml
  - auth_proxy_role_binding.yaml
  - auth_proxy_client_clusterrole.yaml
  - evalhub/evalhub_auth_reviewer_role.yaml
  - evalhub/evalhub_jobs_writer_role.yaml
  - evalhub/evalhub_jobs_writer_binding.yaml
  - evalhub/evalhub_job_config_role.yaml
  - evalhub/evalhub_job_config_binding.yaml
  - evalhub/evalhub_mlflow_access_role.yaml
  - evalhub/evalhub_mlflow_access_binding.yaml
  - evalhub/evalhub_mlflow_jobs_role.yaml
  - evalhub/evalhub_mlflow_jobs_binding.yaml
  - nemoguardrail_editor_role.yaml
  - nemoguardrail_viewer_role.yaml
  - trustyaiservice_editor_role.yaml
  - trustyaiservice_viewer_role.yaml
  - non_admin_lmeval_role.yaml
  - default_lmeval_user_rolebinding.yaml
