apiVersion: trustyai.opendatahub.io.trustyai.opendatahub.io/v1alpha1
kind: TrustyAIService
metadata:
  labels:
    app.kubernetes.io/name: trustyaiservice
    app.kubernetes.io/instance: trustyaiservice-sample
    app.kubernetes.io/part-of: trustyai-service-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: trustyai-service-operator
  name: trustyaiservice-sample
spec:
  # TODO(user): Add fields here
