apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: evalhub
    app.kubernetes.io/name: trustyai-service-operator
  name: evalhub-jobs-writer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: evalhub-jobs-writer
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: system
